// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateLobbyReducer from "../create_lobby_reducer";
import DeleteCourseReducer from "../delete_course_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import PlayAgainReducer from "../play_again_reducer";
import PublishCourseReducer from "../publish_course_reducer";
import ResetBallReducer from "../reset_ball_reducer";
import SaveCourseReducer from "../save_course_reducer";
import SeedBuiltinsReducer from "../seed_builtins_reducer";
import SendChatReducer from "../send_chat_reducer";
import SendEmoteReducer from "../send_emote_reducer";
import SetCharacterReducer from "../set_character_reducer";
import SetColorReducer from "../set_color_reducer";
import SetNameReducer from "../set_name_reducer";
import SetSettingsReducer from "../set_settings_reducer";
import ShootReducer from "../shoot_reducer";
import StartGameReducer from "../start_game_reducer";
import UndoShotReducer from "../undo_shot_reducer";

export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type DeleteCourseParams = __Infer<typeof DeleteCourseReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type PlayAgainParams = __Infer<typeof PlayAgainReducer>;
export type PublishCourseParams = __Infer<typeof PublishCourseReducer>;
export type ResetBallParams = __Infer<typeof ResetBallReducer>;
export type SaveCourseParams = __Infer<typeof SaveCourseReducer>;
export type SeedBuiltinsParams = __Infer<typeof SeedBuiltinsReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SendEmoteParams = __Infer<typeof SendEmoteReducer>;
export type SetCharacterParams = __Infer<typeof SetCharacterReducer>;
export type SetColorParams = __Infer<typeof SetColorReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetSettingsParams = __Infer<typeof SetSettingsReducer>;
export type ShootParams = __Infer<typeof ShootReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type UndoShotParams = __Infer<typeof UndoShotReducer>;

