// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostId: __t.identity().name("host_id"),
  status: __t.u8(),
  phase: __t.u8(),
  courseId: __t.u64().name("course_id"),
  courseName: __t.string().name("course_name"),
  holeCount: __t.u8().name("hole_count"),
  holeId: __t.u64().name("hole_id"),
  isPublic: __t.bool().name("is_public"),
  holeIndex: __t.u8().name("hole_index"),
  phaseTicks: __t.u32().name("phase_ticks"),
  holeTick: __t.u32().name("hole_tick"),
  maxStrokes: __t.u8().name("max_strokes"),
  holeSecs: __t.u16().name("hole_secs"),
  collisions: __t.bool(),
  round: __t.u16(),
  championName: __t.string().name("champion_name"),
  createdAt: __t.timestamp().name("created_at"),
  waterPenalty: __t.bool().name("water_penalty"),
  powerMul: __t.u8().name("power_mul"),
  championshipLeg: __t.u64().name("championship_leg"),
});
