// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  lobbyId: __t.u64().name("lobby_id"),
  color: __t.u8(),
  seat: __t.u8(),
  online: __t.bool(),
  offlineTicks: __t.u16().name("offline_ticks"),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  teleTicks: __t.u8().name("tele_ticks"),
  resting: __t.bool(),
  holed: __t.bool(),
  strokes: __t.u8(),
  total: __t.u16(),
  holeScores: __t.byteArray().name("hole_scores"),
  safeX: __t.f32().name("safe_x"),
  safeY: __t.f32().name("safe_y"),
  struck: __t.bool(),
  finishedTick: __t.u32().name("finished_tick"),
  shotSeq: __t.u32().name("shot_seq"),
  eventKind: __t.u8().name("event_kind"),
  eventSeq: __t.u32().name("event_seq"),
  eventPower: __t.f32().name("event_power"),
  emote: __t.u8(),
  emoteSeq: __t.u32().name("emote_seq"),
  lastChat: __t.u64().name("last_chat"),
});
