// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  courseId: __t.u64(),
  isPublic: __t.bool(),
  maxStrokes: __t.u8(),
  holeSecs: __t.u16(),
  collisions: __t.bool(),
  waterPenalty: __t.bool(),
  powerMul: __t.u8(),
};
