// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u8(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const Course = __t.object("Course", {
  id: __t.u64(),
  ownerId: __t.identity(),
  authorName: __t.string(),
  name: __t.string(),
  holeCount: __t.u8(),
  totalPar: __t.u16(),
  published: __t.bool(),
  builtin: __t.bool(),
  plays: __t.u32(),
  rev: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  ratingSum: __t.u32(),
  ratingCount: __t.u32(),
});
export type Course = __Infer<typeof Course>;

export const Hole = __t.object("Hole", {
  id: __t.u64(),
  courseId: __t.u64(),
  index: __t.u8(),
  name: __t.string(),
  par: __t.u8(),
  data: __t.string(),
});
export type Hole = __Infer<typeof Hole>;

export const LegResult = __t.object("LegResult", {
  id: __t.u64(),
  legId: __t.u64(),
  placings: __t.array(__t.identity()),
  names: __t.array(__t.string()),
  finishedAt: __t.timestamp(),
});
export type LegResult = __Infer<typeof LegResult>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  code: __t.string(),
  hostId: __t.identity(),
  status: __t.u8(),
  phase: __t.u8(),
  courseId: __t.u64(),
  courseName: __t.string(),
  holeCount: __t.u8(),
  holeId: __t.u64(),
  isPublic: __t.bool(),
  holeIndex: __t.u8(),
  phaseTicks: __t.u32(),
  holeTick: __t.u32(),
  maxStrokes: __t.u8(),
  holeSecs: __t.u16(),
  collisions: __t.bool(),
  round: __t.u16(),
  championName: __t.string(),
  createdAt: __t.timestamp(),
  waterPenalty: __t.bool(),
  powerMul: __t.u8(),
  championshipLeg: __t.u64(),
});
export type Lobby = __Infer<typeof Lobby>;

export const MyCourses = __t.object("MyCourses", {});
export type MyCourses = __Infer<typeof MyCourses>;

export const MyRatings = __t.object("MyRatings", {});
export type MyRatings = __Infer<typeof MyRatings>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  lobbyId: __t.u64(),
  color: __t.u8(),
  seat: __t.u8(),
  online: __t.bool(),
  offlineTicks: __t.u16(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  vz: __t.f32(),
  teleTicks: __t.u8(),
  resting: __t.bool(),
  holed: __t.bool(),
  strokes: __t.u8(),
  total: __t.u16(),
  holeScores: __t.byteArray(),
  safeX: __t.f32(),
  safeY: __t.f32(),
  struck: __t.bool(),
  finishedTick: __t.u32(),
  shotSeq: __t.u32(),
  eventKind: __t.u8(),
  eventSeq: __t.u32(),
  eventPower: __t.f32(),
  emote: __t.u8(),
  emoteSeq: __t.u32(),
  lastChat: __t.u64(),
  characterId: __t.u8(),
  ready: __t.bool(),
  kicked: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Rating = __t.object("Rating", {
  id: __t.u64(),
  courseId: __t.u64(),
  identity: __t.identity(),
  stars: __t.u8(),
  updatedAt: __t.timestamp(),
});
export type Rating = __Infer<typeof Rating>;

export const RollClock = __t.object("RollClock", {
  identity: __t.identity(),
  ticks: __t.u32(),
});
export type RollClock = __Infer<typeof RollClock>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Session = __Infer<typeof Session>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
});
export type TickTimer = __Infer<typeof TickTimer>;

